language: php

php:
  - 7.2

cache:
  directories:
    - node_modules
    - vendor
    

before_script:
  - cp .env.travis .env
  - mysql -e 'create database homestead_test;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit